// Loads, runs, unloads the plugin. Easy for development to unlock the plugin DLL

global proc maya2glTF_exporter(string $cmd) {
	print ("Executing "+$cmd+"...\n");

	string $min = `playbackOptions -q -min`;
	string $max = `playbackOptions -q -max`;
	float $fps = `currentTimeUnitToFPS`;

	string $copyright = "Anonymous 2018";

	string $sn = `file -q -sn`;
	$sn = `tolower $sn`;
    if (`match "anim" $sn` == "anim") {
		if (catch(`maya2glTF -copyright $copyright -acn "clip" -ast $min -aet $max -afr $fps -outputFolder "C:/temp/glTF"`) ) {
			print "Failed!\n";
		} 
	} else {
		if (catch(`maya2glTF -copyright $copyright -outputFolder "C:/temp/glTF"`) ) {
			print "Failed!\n";
		} 
	}

	print ("Unloading maya2glTF...");
	unloadPlugin("maya2glTF");
}

unloadPlugin  "maya2glTF";
loadPlugin -rc maya2glTF_exporter;
loadPlugin -ac maya2glTF_exporter  "maya2glTF" ;
